In [1]:
# Câu 1:
import numpy as np
def compute_vector_length(vector):
    return np.linalg.norm(vector)

vector = np.array([-2, 4, 9, 21])
result = compute_vector_length([vector])
print(round(result, 2))

23.28


In [2]:
# Câu 2:
def compute_dot_product(v1, v2):
  return np.dot(v1, v2)

v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = compute_dot_product(v1, v2)
print(round(result, 2))

4


In [3]:
# Câu 3:
x = np.array([[1, 2],
              [3, 4]])
k = np.array([1, 2])
print('result  \n', x.dot(k))

result  
 [ 5 11]


In [4]:
# Câu 4:
x = np.array([[-1, 2],
              [3, -4]])
k = np.array([1, 2])
print('result \n', x@k)

result 
 [ 3 -5]


In [5]:
# Câu 5:
def matrix_multi_vector(m, v):
    return np.dot(m, v)
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


In [6]:
# Câu 6:
def matrix_multi_matrix(m1, m2):
    return np.dot(m1, m2)
m1 = np.array([[0,1,2],[2,-3,1]])
m2 = np.array([[1, -3], [6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


In [7]:
# Câu 7:
m1 = np.eye(3)
m2 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
result = m1@m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [8]:
# Câu 8:
m1 = np.eye(2)
m1 = np.reshape(m1, (-1, 4)) [0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)

[5. 5. 5. 5.]


In [9]:
# Câu 9:
m1 = np.array([[1, 2], [3, 4]])
m1 = np.reshape(m1, (-1,4), "F") [0]
m2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
result = m1@m2
print(result)


[29 29 29 29]


In [10]:
# Câu 10:
def inverse_matrix(m):
    return np.linalg.inv(m)
m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [11]:
# Câu 11:
def compute_eigenvalues_eigenvectors(matrix):
  eigenvalues, eigenvectors = np.linalg.eig(matrix)
  return eigenvalues, eigenvectors
matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [12]:
# Câu 12:
def compute_cosine(v1, v2):
  cos_sim = compute_dot_product(v1,v2) / (compute_vector_length(v1)*compute_vector_length(v2))

  return cos_sim

x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x, y)
print(round(result, 3))

0.577
